# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "b01e623222d86bb51bd89e8347d47dd9dd1bf2b4dd40513e2fbcedd95a2da745"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b23fb8a89015e88865fd2a8ceb9792902c53b0254872407daadec60ab798642f"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f16822670ecf8d0ef2b57451ba77eed0146c5c64820b6472ccf1abce4e67785a"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65a4564fa8e766e95bc90ad775d76ae264ec34b9eee8ac503b774fdb3ef22cd6"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/NicholasCullenCooper/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
