# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "120615aa26c10cb5fae98c6d71754e1484e0bc72a8c5af9a8d87e70f68c9ea04"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9a3e9f8f9144721a310680bd599bcc1e61878353f8fe9ff8a12b5084de12c86"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88ddfca613c8bd24349dd0e737a810bc4909cba1079a94a567ba5836c80ab2d8"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1977239c803587627df761f5eec416bfa9f184d65ad08f2aa83a4148ae7cc4a0"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/NicholasCullenCooper/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
