# This file was generated by GoReleaser. DO NOT EDIT.
cask "csaw" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "314b14e5e3908c0c8b531fe88ad03a139f1de7fc4c44fc9d7300df6b26781134"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1f24079f9d0a3ba4b5ef67a8d6adc0a396bed744bec8c7383950b233faed069"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c13e6f913b7893bf9b4143681a40d4a49c637eff73610a0939e9480e9e3b6fa"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "baa1c454c6bc3961d4efb70cbb9da36b430b3984c6614c3577165d464361e21a"
      url "https://github.com/NicholasCullenCooper/csaw/releases/download/v#{version}/csaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "csaw"
  desc "Mount, not install. AI workspace configuration from git-backed registries."
  homepage "https://github.com/NicholasCullenCooper/csaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "csaw"

  # No zap stanza required

end
